import { parseAbi } from "viem";

// Every signature here was generated mechanically via `forge inspect <Contract>
// abi --json` against the real deployed Duck-Family-Contract sources — not
// hand-typed. This is a DIFFERENT (larger) surface than ../../../interface's
// chain/abis.js: that file only has the trader-facing functions; this one
// adds every owner-only admin function this dashboard exposes. Error entries
// are included so viem can decode a revert's 4-byte selector into a readable
// name (e.g. "OwnableUnauthorizedAccount(0x...)" when the wrong wallet is
// connected) instead of a raw, unreadable selector.

export const DUCK_INCUBATION_ABI = parseAbi([
  "function owner() view returns (address)",
  "function creationFee() view returns (uint256)",
  "function platformWallet() view returns (address)",
  "function platformToken() view returns (address)",
  "function minCurveBps() view returns (uint256)",
  "function minLiquidityBps() view returns (uint256)",
  "function minSupply() view returns (uint256)",
  "function maxSupply() view returns (uint256)",
  "function tokenImpl() view returns (address)",
  "function locker() view returns (address)",
  "function quoteTokenAllowed(address) view returns (bool)",
  "function v4PositionManager() view returns (address)",
  "function v4Singleton() view returns (address)",
  "function v4Permit2() view returns (address)",
  "function v4Hook() view returns (address)",
  "function setCreationFee(uint256 fee_)",
  "function setQuoteTokenAllowed(address token_, bool allowed_)",
  "function setAllocationBounds(uint256 minCurveBps_, uint256 minLiquidityBps_)",
  "function setSupplyBounds(uint256 minSupply_, uint256 maxSupply_)",
  "function setTokenImpl(address impl_)",
  "function setLocker(address locker_)",
  "function setDexConfig(address positionManager_, address singleton_, address permit2_, address hook_)",
  "function setPlatformWallet(address wallet_)",
  "function setPlatformToken(address token_)",
  "function emergencyMigrate(address token_)",
  "function rescueETH(address to)",
  "function rescueToken(address token_, address to)",
  "error ActivePool()", "error AddressEmptyCode(address target)", "error AlreadyMigrated()",
  "error AntibotBlocksOutOfRange()", "error ApprovalFailed()", "error CloneFailed()", "error DeadlineExpired()",
  "error ERC1967InvalidImplementation(address implementation)", "error ERC1967NonPayable()", "error ExceedsSoldSupply()",
  "error FailedCall()", "error InsufficientContractBalance()", "error InsufficientCreationFee(uint256 required, uint256 provided)",
  "error InsufficientOutput()", "error InsufficientPoolQuote()", "error InvalidAllocation()", "error InvalidFeeSplitBps()",
  "error InvalidHookFeeBps()", "error InvalidInitialization()", "error InvalidMarketCaps()", "error InvalidSupply()",
  "error LiquidityReserveViolation()", "error MigrationPending()", "error MigrationTargetNotReached()",
  "error NativeNotAccepted()", "error NativeQuoteNoSwapNeeded()", "error NativeTransferFailed()", "error NotCreator()",
  "error NotInitializing()", "error NotMigrated()", "error NotSelf()", "error OwnableInvalidOwner(address owner)",
  "error OwnableUnauthorizedAccount(address account)", "error PendingValueMismatch()", "error QuoteTokenNotAllowed()",
  "error Reentrancy()", "error RouteUnavailable()", "error SlippageTooFewTokens()", "error SlippageTooLittleQuote()",
  "error TimelockNotExpired()", "error TimelockNotQueued()", "error TooManyFeeSplits()", "error TransferFailed()",
  "error UUPSUnauthorizedCallContext()", "error UUPSUnsupportedProxiableUUID(bytes32 slot)", "error Unauthorized()",
  "error UnknownToken()", "error VanityAddressRequired()", "error ZeroAddress()", "error ZeroAmount()",
]);

export const DUCK_LAUNCHER_ABI = parseAbi([
  "function owner() view returns (address)",
  "function platformWallet() view returns (address)",
  "function platformToken() view returns (address)",
  "function launchFee() view returns (uint256)",
  "function tokenImpl() view returns (address)",
  "function quoteTokens(address) view returns (bool)",
  "function dexes(address) view returns (address singleton, address permit2, address hook, bool enabled)",
  "function setPlatformWallet(address wallet)",
  "function setPlatformToken(address token)",
  "function setTokenImpl(address tokenImpl_)",
  "function setLaunchFee(uint256 fee_)",
  "function addDex(address positionManager_, address singleton_, address permit2_, address hook_)",
  "function disableDex(address positionManager_)",
  "function addQuoteToken(address token_)",
  "function disableQuoteToken(address token_)",
  "function rescueETH(address to_, uint256 amount_)",
  "function rescueERC20(address token_, address to_, uint256 amount_)",
  "error AddressEmptyCode(address target)", "error ApprovalFailed()", "error CloneFailed()",
  "error ERC1967InvalidImplementation(address implementation)", "error ERC1967NonPayable()", "error FailedCall()",
  "error HookRequired()", "error InstantBuyFailed()", "error InsufficientOutput()", "error InvalidHookFeeBps()",
  "error InvalidInitialization()", "error InvalidTickRange()", "error NotInitializing()",
  "error OwnableInvalidOwner(address owner)", "error OwnableUnauthorizedAccount(address account)",
  "error PendingValueMismatch()", "error PoolAlreadyExists()", "error ReentrancyGuardReentrantCall()",
  "error TimelockNotExpired()", "error TimelockNotQueued()", "error TransferFailed()",
  "error UUPSUnauthorizedCallContext()", "error UUPSUnsupportedProxiableUUID(bytes32 slot)", "error Unauthorized()",
  "error UnsupportedDex()", "error UnsupportedQuoteToken()", "error VanityMismatch()", "error WrongFee()",
  "error ZeroAddress()", "error ZeroAmount()",
]);

export const DUCK_RAISE_ABI = parseAbi([
  "function owner() view returns (address)",
  "function platformWallet() view returns (address)",
  "function platformToken() view returns (address)",
  "function campaignFee() view returns (uint256)",
  "function campaignDuration() view returns (uint256)",
  "function contributorBps() view returns (uint256)",
  "function lpBps() view returns (uint256)",
  "function tokenImpl() view returns (address)",
  "function locker() view returns (address)",
  "function weth() view returns (address)",
  "function quoteAssetAllowed(address) view returns (bool)",
  "function v4PositionManager() view returns (address)",
  "function v4Singleton() view returns (address)",
  "function v4Permit2() view returns (address)",
  "function v4Hook() view returns (address)",
  "function setQuoteAssetAllowed(address token_, bool allowed_)",
  "function setTokenImpl(address tokenImpl_)",
  "function setLocker(address locker_)",
  "function setWeth(address weth_)",
  "function setDexConfig(address positionManager_, address singleton_, address permit2_, address hook_)",
  "function setPlatformWallet(address wallet)",
  "function setPlatformToken(address token)",
  "function setCampaignFee(uint256 fee_)",
  "function setSupplySplit(uint256 contributorBps_, uint256 lpBps_)",
  "function setCampaignDuration(uint256 duration_)",
  "error AddressEmptyCode(address target)", "error AlreadyFinalized()", "error ApprovalFailed()",
  "error CampaignFailed_()", "error CampaignNotFound()", "error CampaignSucceeded_()", "error CloneFailed()",
  "error DeadlineNotPassed()", "error DeadlinePassed()", "error ERC1967InvalidImplementation(address implementation)",
  "error ERC1967NonPayable()", "error FailedCall()", "error HookNotSet()", "error InsufficientOutput()",
  "error InvalidBps()", "error InvalidHookFeeBps()", "error InvalidInitialization()", "error NotFinalized()",
  "error NotInitializing()", "error NotLiveYet()", "error NothingToClaim()", "error OwnableInvalidOwner(address owner)",
  "error OwnableUnauthorizedAccount(address account)", "error PendingValueMismatch()", "error PoolAlreadyExists()",
  "error QuoteAssetNotAllowed()", "error ReentrancyGuardReentrantCall()", "error SwapFailed()",
  "error TimelockNotExpired()", "error TimelockNotQueued()", "error TransferFailed()",
  "error UUPSUnauthorizedCallContext()", "error UUPSUnsupportedProxiableUUID(bytes32 slot)", "error Unauthorized()",
  "error VanityMismatch()", "error WrongFee()", "error ZeroAddress()", "error ZeroAmount()",
]);

export const DUCK_LOCKER_ABI = parseAbi([
  "function owner() view returns (address)",
  "function platformWallet() view returns (address)",
  "function platformToken() view returns (address)",
  "function isLauncher(address) view returns (bool)",
  "function tokenCount() view returns (uint256)",
  "function allTokens(uint256) view returns (address)",
  "function creatorOf(address token) view returns (address)",
  "function positions(address) view returns (uint256 tokenId, address token0, address token1, bytes32 poolId, address hook, address positionManager)",
  "function addLauncher(address launcher_)",
  "function removeLauncher(address launcher_)",
  "function setPlatformWallet(address wallet)",
  "function setPlatformToken(address token)",
  "function claimAllFees()",
  "function claimFees(address token)",
  "function claimFeesRange(uint256 from, uint256 to)",
  "error AddressEmptyCode(address target)", "error AlreadyRegistered()",
  "error ERC1967InvalidImplementation(address implementation)", "error ERC1967NonPayable()", "error FailedCall()",
  "error InvalidInitialization()", "error NotAuthorized()", "error NotInitializing()", "error NotLauncher()",
  "error OwnableInvalidOwner(address owner)", "error OwnableUnauthorizedAccount(address account)",
  "error PendingValueMismatch()", "error TimelockNotExpired()", "error TimelockNotQueued()", "error TransferFailed()",
  "error UUPSUnauthorizedCallContext()", "error UUPSUnsupportedProxiableUUID(bytes32 slot)", "error Unauthorized()",
  "error UnknownToken()", "error ZeroAddress()",
]);

export const DUCK_HOOK_ABI = parseAbi([
  "function owner() view returns (address)",
  "function platformWallet() view returns (address)",
  "function ctoFee() view returns (uint256)",
  "function isLauncher(address) view returns (bool)",
  "function pools(bytes32) view returns (address token, address quoteCurrency, bool tokenIsCurrency0, address creator, uint256 launchTimestamp, bool registered, uint256 hookFeeBps)",
  "function ctoApplications(bytes32) view returns (address applicant, address newCreator, uint256 paid)",
  "function accruedFees(bytes32) view returns (uint256)",
  "function addLauncher(address launcher_)",
  "function removeLauncher(address launcher_)",
  "function setCTOFee(uint256 fee_)",
  "function setPlatformWallet(address wallet_)",
  "function transferOwnership(address newOwner)",
  "function approveCTO(bytes32 poolId)",
  "function rejectCTO(bytes32 poolId)",
  "error AlreadyRegistered()", "error CTOApplicationPending()", "error InsufficientCTOFee()",
  "error InvalidFeeSplitBps()", "error InvalidHookFeeBps()", "error NoCTOApplication()", "error NotCreator()",
  "error NotLauncher()", "error NotOwner()", "error NotPoolManager()", "error NotRegistered()",
  "error SameBlockSwap()", "error TooManyFeeSplits()", "error TransferFailed()", "error ZeroAddress()",
]);

export const DUCK_META_OVERRIDE_ABI = parseAbi([
  "function owner() view returns (address)",
  "function pendingOwner() view returns (address)",
  "function isRegistered(address) view returns (bool)",
  "function metaURI(address) view returns (string)",
  "function getMetaURI(address token) view returns (bool overridden, string uri)",
  "function registerToken(address token, string metaURI_)",
  "function updateMetaURI(address token, string metaURI_)",
  "function unregisterToken(address token)",
  "function transferOwnership(address newOwner)",
  "function acceptOwnership()",
  "function renounceOwnership()",
  "error NotRegistered()", "error OwnableInvalidOwner(address owner)", "error OwnableUnauthorizedAccount(address account)",
  "error ZeroAddress()",
]);
